name: Build

on: [push, workflow_dispatch, workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew installDist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: build/install/${YOUR_APP_NAME}/lib