name: Deploy
on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [build]

    # Important: must be run from Linux.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-result
          path: ./artifacts

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v17.0
        with:
          command: make site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1