name: Deploy to GitHub
on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: build-result
          path: ./artifacts
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v17.0
        with:
          command: make windows-zip
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-result
          path: output